apiVersion: v1
kind: ServiceAccount
metadata:
  name: vllm-metal-epp
  namespace: llm-d-metal
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: vllm-metal-epp
  namespace: llm-d-metal
rules:
- apiGroups:
  - "inference.networking.x-k8s.io"
  resources:
  - "inferenceobjectives"
  - "inferencemodelrewrites"
  verbs:
  - "get"
  - "watch"
  - "list"
- apiGroups:
  - ""
  resources:
  - "pods"
  verbs:
  - "get"
  - "watch"
  - "list"
- apiGroups:
  - "inference.networking.k8s.io"
  resources:
  - "inferencepools"
  verbs:
  - "get"
  - "watch"
  - "list"
- apiGroups:
  - "authentication.k8s.io"
  resources:
  - "tokenreviews"
  verbs:
  - "create"
- apiGroups:
  - "authorization.k8s.io"
  resources:
  - "subjectaccessreviews"
  verbs:
  - "create"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vllm-metal-epp-binding
  namespace: llm-d-metal
subjects:
- kind: ServiceAccount
  name: vllm-metal-epp
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: vllm-metal-epp
